/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "梦回清尘",
  "description": "人注定要受自由之苦",
  "base": "/bloglxd/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/bloglxd/images/Logo2.png"
      }
    ],
    [
      "meta",
      {
        "name": "author",
        "content": "梦回清尘"
      }
    ],
    [
      "meta",
      {
        "name": "keywords",
        "content": "笔记，项目"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "Hero 标题",
        "tagline": "Hero 副标题",
        "actionText": "快速上手 →",
        "features": [
          {
            "title": "简洁至上",
            "details": "以 Markdown 为中心的项目结构，以最少的配置帮助你专注于写作。"
          },
          {
            "title": "Vue驱动",
            "details": "享受 Vue + webpack 的开发体验，在 Markdown 中使用 Vue 组件，同时可以使用 Vue 来开发自定义主题。"
          },
          {
            "title": "高性能",
            "details": "VuePress 为每个页面预渲染生成静态的 HTML，同时在页面被加载的时候，将作为 SPA 运行。"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2018-present Evan You"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-5c8be30c",
      "path": "/"
    },
    {
      "title": "关于我",
      "frontmatter": {},
      "regularPath": "/about.html",
      "relativePath": "about.md",
      "key": "v-d07e3e22",
      "path": "/about.html",
      "headers": [
        {
          "level": 2,
          "title": "关于我",
          "slug": "关于我"
        }
      ]
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    }
  ],
  "themeConfig": {
    "logo": "/images/logo.png",
    "lastUpdated": "更新时间",
    "nav": [
      {
        "text": "主页",
        "link": "/"
      },
      {
        "text": "笔记",
        "link": "/about"
      },
      {
        "text": "项目",
        "link": "https://google.com"
      },
      {
        "text": "工具",
        "items": [
          {
            "text": "Group1",
            "items": [
              {
                "text": "Chinese",
                "link": "/language/chinese/"
              },
              {
                "text": "Japanese",
                "link": "/language/japanese/"
              }
            ]
          },
          {
            "text": "Group2",
            "items": [
              {
                "text": "Chinese",
                "link": "/language/chinese/"
              },
              {
                "text": "Japanese",
                "link": "/language/japanese/"
              }
            ]
          }
        ]
      },
      {
        "text": "联系我",
        "link": "/guide/"
      }
    ]
  }
}